spring.application.name=codelearn

# Server Configuration
server.port=8081
server.address=0.0.0.0

# Database Configuration (PostgreSQL - Neon)
spring.datasource.url=jdbc:postgresql://ep-spring-cell-ab4f8r2p-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2qUsuybN9fJB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ=
jwt.expiration=86400000

