import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { Badge } from "./Badge";
import { Card } from "./Card";
import Avatar from "./Avatar";
export var CourseCard = function (_a) {
    var course = _a.course;
    return (_jsx(Link, { to: "/courses/".concat(course.id), className: "group block h-full", children: _jsxs(Card, { variant: "gradient", hover: true, className: "h-full flex flex-col gap-4 group-hover:border-primary-200 transition-all duration-300", children: [_jsxs("div", { className: "relative -mx-6 -mt-6 mb-2 h-40 overflow-hidden rounded-t-2xl bg-gradient-to-br from-primary-500 via-secondary-500 to-primary-600 flex items-center justify-center", children: [_jsx("div", { className: "text-6xl opacity-20", children: "\uD83D\uDCDA" }), _jsx("div", { className: "absolute inset-0 bg-black/10 group-hover:bg-black/0 transition-all duration-300" })] }), _jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx(Avatar, { name: course.authorName, size: "sm" }), _jsx("div", { className: "flex-1 min-w-0", children: _jsx("p", { className: "text-xs font-semibold text-slate-600 truncate", children: course.authorName }) }), _jsxs(Badge, { variant: "primary", size: "sm", children: [course.supportsCount, " modules"] })] }), _jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "text-lg font-bold text-slate-900 mb-2 line-clamp-2 group-hover:text-primary-700 transition-colors", children: course.title }), _jsx("p", { className: "text-sm text-slate-600 line-clamp-3", children: course.description })] }), _jsxs("div", { className: "flex items-center justify-between pt-4 border-t border-slate-100", children: [_jsxs("span", { className: "flex items-center gap-2 text-sm font-semibold text-primary-600 group-hover:text-primary-700 transition-colors", children: [_jsx("span", { children: "View Course" }), _jsx("svg", { className: "w-4 h-4 group-hover:translate-x-1 transition-transform", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M13 7l5 5m0 0l-5 5m5-5H6" }) })] }), _jsx("div", { className: "flex items-center gap-1", children: _jsx("div", { className: "h-1.5 w-16 bg-slate-200 rounded-full overflow-hidden", children: _jsx("div", { className: "h-full w-0 bg-accent-500 rounded-full" }) }) })] })] }) }));
};
