import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "./Button";
import { Badge } from "./Badge";
import { SupportTypeIcon } from "./SupportTypeIcon";
export var ModuleItem = function (_a) {
    var module = _a.module, onComplete = _a.onComplete, _b = _a.loading, loading = _b === void 0 ? false : _b, index = _a.index;
    return (_jsxs("div", { className: "group relative flex flex-col gap-4 rounded-xl border-2 p-5 transition-all duration-200 ".concat(module.completed
            ? "border-accent-200 bg-accent-50/50"
            : "border-slate-200 bg-white hover:border-primary-300 hover:shadow-md"), children: [index !== undefined && (_jsx("div", { className: "absolute -left-3 -top-3 h-8 w-8 rounded-full bg-gradient-to-br from-primary-600 to-secondary-600 flex items-center justify-center text-white text-sm font-bold shadow-lg", children: index })), _jsxs("div", { className: "flex flex-col sm:flex-row gap-4 sm:items-center sm:justify-between", children: [_jsxs("div", { className: "flex flex-1 items-start gap-4", children: [_jsx("div", { className: "flex-shrink-0 mt-1", children: _jsx(SupportTypeIcon, { type: module.type }) }), _jsxs("div", { className: "flex-1 space-y-2", children: [_jsx("h3", { className: "text-base font-bold text-slate-900 group-hover:text-primary-700 transition-colors", children: module.title }), module.completed && module.completedAt ? (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "h-6 w-6 rounded-full bg-accent-600 flex items-center justify-center text-white text-xs font-bold animate-scale-in", children: "\u2713" }), _jsxs("p", { className: "text-sm text-accent-700 font-medium", children: ["Completed on ", new Date(module.completedAt).toLocaleDateString()] })] })) : (_jsx("p", { className: "text-sm text-slate-600", children: "Click to mark as complete when finished." }))] })] }), _jsx("div", { className: "flex items-center gap-3 sm:flex-shrink-0", children: module.completed ? (_jsx(Badge, { variant: "success", size: "md", dot: true, children: "Completed" })) : (_jsx(Button, { variant: "success", size: "md", onClick: function () { return onComplete === null || onComplete === void 0 ? void 0 : onComplete(module.id); }, loading: loading, disabled: !onComplete || loading, icon: !loading && (_jsx("svg", { className: "w-4 h-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M5 13l4 4L19 7" }) })), children: "Mark Complete" })) })] })] }));
};
