import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "./Button";
import { Badge } from "./Badge";
import { SupportTypeIcon } from "./SupportTypeIcon";
export var SupportItem = function (_a) {
    var support = _a.support, onAccess = _a.onAccess, _b = _a.loading, loading = _b === void 0 ? false : _b;
    var typeColor = support.type === "VIDEO" || support.type === "Video" ? "primary" : "success";
    return (_jsx("div", { className: "group flex flex-col gap-4 rounded-xl border-2 border-slate-200 bg-white p-5 hover:border-primary-300 hover:shadow-md transition-all duration-200", children: _jsxs("div", { className: "flex flex-col sm:flex-row gap-4 sm:items-start sm:justify-between", children: [_jsxs("div", { className: "flex flex-1 items-start gap-4", children: [_jsx("div", { className: "flex-shrink-0 mt-1", children: _jsx(SupportTypeIcon, { type: support.type }) }), _jsxs("div", { className: "flex-1 space-y-2", children: [_jsxs("div", { className: "flex items-start gap-2", children: [_jsx("h3", { className: "text-base font-bold text-slate-900 flex-1 group-hover:text-primary-700 transition-colors", children: support.title }), _jsx(Badge, { variant: typeColor, size: "sm", children: support.type })] }), _jsx("p", { className: "text-sm text-slate-600 leading-relaxed", children: support.description })] })] }), _jsx("div", { className: "sm:flex-shrink-0", children: _jsx(Button, { variant: "outline", size: "md", onClick: function () { return onAccess === null || onAccess === void 0 ? void 0 : onAccess(support.id); }, loading: loading, disabled: !onAccess || loading, icon: !loading && (_jsxs("svg", { className: "w-4 h-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: [_jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M15 12a3 3 0 11-6 0 3 3 0 016 0z" }), _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" })] })), children: "Access Resource" }) })] }) }));
};
